### PR TITLE
chore(project): add initial project structure

### PR DESCRIPTION
**Pull request by Tooa**
This pull request adds the initial project structure. The pull also adds several features:
- Multi Sbt project (common/core)
- Travis CI (commit message validation, build and test validation, code format validation, scalastyle tests)
- Automatic unit test reports with coveralls.io
- Scala style logging framework (subclass or mix-in `LazyLogging`)
- Command line parser `scopt`

### CODE REVIEW

**Comment by Tooa** [comment]
@alexanderpanchenko Can you have a look at this?

**Comment by Tooa** [comment]
Ok. I do the rebase myself. Please write in future one comment or edit your messages.

**Comment by alexanderpanchenko** [comment]
these were comments related to code (check above) + one normal comment :-)

**Comment by Tooa** [comment]
Oh, sry :v: Regarding your workflow question: I suggest to work on single feature branches (maybe prefix with feature or fix) and rebase the code. The pull request should also be just one commit (squash commits) and the fast forward merge should be without an additional merge commit (no `--no-ff`). 

Once I have time, I will summarize the  detailed workflow in `CONTRIBUTING.md` for git beginners.

**Comment by alexanderpanchenko** [comment]
Sound very reasonable. Since I am most likely will not contribute that much to the codebase (i just do not have time due to other projects), you just need to agree on  the rules with other developers like Seid in case of conflicts.

**Pull request merged**
